-- Migration 20: No-op (version column now added in migration 06)
-- Original purpose: Add version column that was missing from migration 12
--
-- This migration is now a no-op because the version column is properly
-- included in migration 06__agent_file_versioning.sql when the table
-- is recreated. Keeping this file to maintain migration sequence.
--
-- For existing databases that already applied migration 20, this no-op
-- ensures no errors occur on re-migration.
