-- Force re-login by deleting all access tokens
-- Note: access tokens are stored in user_setting, not a separate user_access_token table.
-- This migration is intentionally a no-op because the user_access_token table was never created.
